name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller (build script)
        run: |
          ls -la
          pwsh -File build-windows.ps1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rmk-windows-build
          path: |
            build/dist/**
            build/pyinstaller.log
